### ISSUE TITLE
《装甲悪鬼村正》无解的电车难题 - 小鸟的风祭森林

### ISSUE THREAD

**Issue by dangokanako** [dangokanako/blog-comments-gitalk#7]
https://dangokanako.github.io/2023/05/12/%E9%94%90%E8%AF%84/%E8%A3%85%E7%94%B2%E6%82%AA%E9%AC%BC%E6%9D%91%E6%AD%A3/ 

 document.addEventListener('DOMContentLoaded', function () {         const ap = new APlayer({             theme: '#FADFA3',             container: document.getElementById('my-aplayer1'),

**Comment by dangokanako** [comment]
TESTTT

**Comment by Algebraic-Zephyr** [comment]
Markdown Test: 
- TEST1
-  TEST2
Have a nice day, Dango chan
